# -*- coding: utf-8 -*-
"""Module2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vyb_bO9eakx45aKXMe4z3eKJ3NdUalFg
"""

class Sentence :

    def __init__(self, text):
      self.text = text

    def __str__(self):
      self.text = str(self.text)

    def get_next_bigrams(self):
      return str([(x, i.split()[j + 1]) for i in [self.text]
       for j, x in enumerate(i.split()) if j < len(i.split()) - 1])